# Generated by Django 3.1.2 on 2020-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201223_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='film_genre', to='movies.Genre', verbose_name='Жанры'),
        ),
    ]
