# Generated by Django 3.1.2 on 2020-12-24 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201223_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.DateField(default=datetime.date.today, verbose_name='Возраст'),
        ),
    ]
