# Generated by Django 3.1.2 on 2020-12-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_devorced'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='english_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя на английском'),
        ),
    ]
