# Generated by Django 3.1.2 on 2020-12-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='sum_movies',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Количество фильмов'),
        ),
    ]
