# Generated by Django 3.1.2 on 2020-12-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_actor_sum_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='treiler',
            field=models.FileField(null=True, upload_to='treilers/', verbose_name='Трейлер'),
        ),
    ]
