# Generated by Django 3.1.2 on 2020-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_english_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Наименование качества')),
            ],
            options={
                'verbose_name': 'Качество видео',
                'verbose_name_plural': 'Качество видео',
            },
        ),
    ]
