# Generated by Django 3.1.2 on 2020-12-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_quality_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.ManyToManyField(related_name='film_producers', to='movies.Actor', verbose_name='Продюсер'),
        ),
    ]
