# Generated by Django 3.1.2 on 2020-12-25 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_movie_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='russian_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Примьера в России'),
        ),
    ]
