# Generated by Django 3.1.2 on 2020-12-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_russian_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='devorced',
            field=models.ManyToManyField(blank=True, related_name='_actor_devorced_+', to='movies.Actor'),
        ),
    ]
