# Generated by Django 3.1.2 on 2020-12-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20201228_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description_2',
            field=models.TextField(null=True, verbose_name='Подробное описание'),
        ),
    ]
